### ISSUE TITLE
Setup github actions for automated tests

### ISSUE THREAD

**Issue by Manvel** [browser-automation/cba-components#10]

**Comment by Manvel** [comment]
There seem to be still some issues when running puppeteer on Github actions, a simple example below, fails both on `ubuntu-latest` and `macos-latest`

```
const puppeteer = require("puppeteer");
const assert = require("assert");

let browser;

describe("Test", () => {
  before(async () =>
  {
    browser = await puppeteer.launch({headless: false});
  });
  it("testing", () =>
  {
    assert.equal(true, true);
  })
  after(async () =>
  {
    await browser.close();
  })
});
```

Setting `headless: true` fails on `macos-latest`, but works on `ubuntu-latest`.

Failling log:

```


  Test
    1) "before all" hook for "testing"
    2) "after all" hook for "testing"


  0 passing (2s)
  2 failing

  1) Test
       "before all" hook for "testing":
     Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/runners/2.165.2/work/cba-components/cba-components/tests/puppeteer/mocha.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  2) Test
       "after all" hook for "testing":
     TypeError: Cannot read property 'close' of undefined
      at processImmediate (internal/timers.js:456:21)



##[error]The operation was canceled.
```

**Comment by Manvel** [comment]
Test repository is created -> https://github.com/Manvel/github-actions-puppeteer

Using now travis CI instead of Github actions
